cc_test(
    name = "communication_core_test",
    srcs = ["someip_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@communication_core//someip/factory:someip_header_factory",
        ],
    visibility = ["//visibility:public"],
)