
cc_test(
    name = "someip_header_test",
    srcs = ["someip_header_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@communication_core//someip:someip_header"
        ]
)
