cc_library(
    name = "DatabaseLib",
    srcs = ["database.cc"],
    hdrs = [
        "Idatabase.h",
        "database.h",
        "database_element.h",
        "event_element.h",
        "method_element.h",
        "net_interface_element.h",
        "service_element.h",
    ],
    visibility = ["//communication_core/:__subpackages__"],
    deps = ["@core"],
)
