cc_library(
    name = "JsonParser",
    hdrs = ["database_json_parser.h"],
    visibility = ["//communication-core:__subpackages__"],
    deps = [
        "//communication-core/database:DatabaseLib",
        "@com_json//:json",
    ],
)
