cc_library(
    name = "JsonParser",
    hdrs = ["database_json_parser.h"],
    visibility = ["//communication_core/:__subpackages__"],
    deps = [
        "//communication_core/database:DatabaseLib",
        "@com_json//:json",
    ],
)
