name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Bazel
        run: |
          sudo apt install apt-transport-https curl gnupg -y
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update
          sudo apt-get install -y bazel cpplint
          bazel version

      - name: Build core
        run: |
          bazel build //:communication_core

      - name: Build and Run Tests
        run: |
          bazel build //:com_core_test
          cd test
          bazel test //:com_core_test

      - name: Check C++ Syntax
        run: |
          cpp_files=$(find . -name "*.cc" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp")
          total_errors=0
          for file in $cpp_files; do
            errors=$(cpplint --filter=-build/include_subdir --extensions=cc,cpp,h,hpp --linelength=120 --recursive --repository=. --root=src $file | wc -l)
            total_errors=$((total_errors + errors))
          done
          
          if [[ $total_errors -gt 10 ]]; then
            echo "Too many errors ($total_errors), failing the build."
            exit 1
          else
            echo "Acceptable number of errors ($total_errors)."
          fi
  
  
